version: "3.7"

services:
  amazing-object-storage-node-1: &object-storage-node
    image: minio/minio
    command: server --console-address ":9001" /tmp/data
    ports: [ "9001:9001" ] # You can open localhost:9001 in your browser to debug what objects are on this node.
    networks:
      amazing-object-storage:
        # Don't copy those addresses in your application. Use the local docker socket to get them.
        ipv4_address: 169.253.0.2
    environment:
      # Same for the environment variables, use the local docker socket to read it.
      - MINIO_ACCESS_KEY=ring
      - MINIO_SECRET_KEY=treepotato

  amazing-object-storage-node-2:
    <<: *object-storage-node
    ports: [ "9002:9001" ] # You can open localhost:9002 in your browser to debug what objects are on this node.
    networks:
      amazing-object-storage:
        ipv4_address: 169.253.0.3
    environment:
      - MINIO_ACCESS_KEY=maglev
      - MINIO_SECRET_KEY=baconpapaya

  amazing-object-storage-node-3:
    <<: *object-storage-node
    ports: [ "9003:9001" ] # You can open localhost:9003 in your browser to debug what objects are on this node.
    networks:
      amazing-object-storage:
        ipv4_address: 169.253.0.4
    environment:
      - MINIO_ACCESS_KEY=rendezvous
      - MINIO_SECRET_KEY=bluegreen

  gateway-container: # Here, this is where you can configure your gateway.
    # Feel free to change configuration options of this container, like the image, or the Dockerfile itself.
    depends_on:
      - amazing-object-storage-node-1
      - amazing-object-storage-node-2
      - amazing-object-storage-node-3
    build: .
    ports: [ "3000:3000" ]
    environment:
      - DOCKER_API_VERSION=1.43
      - DEBUG=true
    networks:
      amazing-object-storage:
        ipv4_address: 169.253.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  amazing-object-storage:
    ipam:
      driver: default
      config:
        - subnet: 169.253.0.0/24
          gateway: 169.253.0.1
